# Generated by Django 3.1b1 on 2020-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='logo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
